
/*
Branch Target Buffer stores target address
associated with a particular index. 
Index is generated by g-share predictor.

Updated during instruction commit with
synchronous write on positive clock edge. 
*/



module branch_target_buffer #(parameter I = 7,DEPTH = 256, W = 31)
                            (input logic clk,
                             input logic[I:0] index,wr_index,
                             input logic[W:0] update_addr,
                             input logic update_predictor,
                             output logic btb_hit,
                             output logic[W:0] target_addr);
                             
                             /*255 entry buffer that holds target address for branch prediction*/
                             logic[W+1:0] buffer[DEPTH-1:0];
                             
                             initial begin
                                for (int i=0; i<DEPTH; i=i+1) begin
                                    buffer[i] = 0;
                                end
                             end

                             always_ff @(posedge clk) begin
                                /*Synchronous write*/
                                if(update_predictor) begin
                                    buffer[wr_index] <= {1'b1,update_addr};
                                end
                             end
                             
                             logic[W+1:0] prediction;
                             always_ff @(negedge clk)begin
                                prediction <= buffer[index];
                             end
                             
                             assign target_addr = prediction[W:0];
                             assign btb_hit = prediction[W+1];
endmodule
