
/*
Pattern history table stores predictions
associated with a particular PC. 
Index into PHT is generated by g-share
predictor which hashes the instruction's PC.

Each entry is a 2 bit saturating counter
with most significant bit determining 
prediction direction(taken for 1, not
taken for '0). Entries 00,01,10,11 
represent conditions strongly not taken, 
weakly not taken, weakly taken and strongly 
taken.

For any given branch instruction, PHT
table is updated during instruction commit.
PHT table is restricted to branch
instructions. 
*/



module pattern_history_table #(parameter C = 1,I = 7,DEPTH = 256, W = 31)
                            (input logic clk,
                             input logic[I:0] index,wr_index,
                             input logic update_predictor,
                             input logic[C:0] updated_state,
                             output logic[C:0] predicted_state);
                             
                             /*256 entry buffer that holds predictions directions*/
                             logic[C:0] buffer[DEPTH-1:0];
                             
                             initial begin
                                for (int i=0; i<DEPTH; i=i+1) begin
                                    buffer[i] = 0;
                                end
                             end
                             
                             always_ff @(posedge clk)begin
                                if(update_predictor)begin
                                    buffer[wr_index] <= updated_state;
                                end
                             end

                             always_ff @(negedge clk) begin
                                /*Synchronous read*/
                                predicted_state <= buffer[index];
                             end
endmodule
