#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Dec 04 23:47:25 PST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ri_rs_tb_func_synth -key {Post-Synthesis:sim_1:Functional:ri_rs_tb} -tclbatch ri_rs_tb.tcl -log simulate.log"
xsim ri_rs_tb_func_synth -key {Post-Synthesis:sim_1:Functional:ri_rs_tb} -tclbatch ri_rs_tb.tcl -log simulate.log

